window.STATIONS_DATA = {
  antwerp: {
    name: "Antwerp",
    country: "Belgium",
    description: "Rail photography in Antwerp.",
    photos: [
      {
        series: "antwerp-photo-0",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Antwerp/Antwerp_HLE1804M6.webp",
        alt: "Antwerp HLE 1804 + 8x M6",
        label: "Antwerp",
        numbers: "1804",
        date: "25 February 2026",
        consist: [
          { kind: "traction", label: "HLE 1804", active: true },
          { kind: "carriage", label: "8x M6", active: true },
        ],
      },
    ],
  },
  "brussels-midi": {
    name: "Brussels-Midi",
    country: "Belgium",
    description: "Rail photography in Brussels-Midi.",
    photos: [
      {
        series: "brussels-midi-photo-0",
        isMain: true,
        operator: "NMBS/SNCB, ÖBB",
        src: "../images/Belgium/Brussels-Midi/Brussels_HLE1834NightJet.webp",
        alt: "Brussels-Midi HLE 1834 + NightJet",
        label: "Brussels-Midi",
        numbers: "1834",
        date: "7 Februari 2025",
        consist: [
          { kind: "traction", label: "HLE 1834", active: true },
          { kind: "carriage", label: "NightJet" },
        ],
      },
    ],
  },
  duffel: {
    name: "Duffel",
    country: "Belgium",
    description: "Rail photography in Duffel.",
    photos: [
      {
        series: "duffel-photo-0",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Duffel/Duffel_M4HLE27.webp",
        alt: "Duffel 7x M4 + HLE 27",
        label: "Duffel",
        numbers: "",
        date: "",
        consist: [
          { kind: "carriage", label: "7x M4", active: true },
          { kind: "traction", label: "HLE 27", active: true },
        ],
      },
    ],
  },
  eupen: {
    name: "Eupen",
    country: "Belgium",
    description: "Rail photography in Eupen.",
    photos: [
      {
        series: "eupen-photo-0",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Eupen/IMG_4764.webp",
        alt: "Eupen HLE 1828 + I10 + 7x M7 + HLE 1837",
        label: "Eupen",
        numbers:
          "1837, 72144, 73032, 79010, 73006, 73010, 72010, 72054, 12773, 1828",
        date: "8 March 2026",
        consist: [
          { kind: "traction", label: "HLE 1828", active: true },
          { kind: "carriage", label: "I10" },
          { kind: "carriage", label: "7x M7" },
          { kind: "traction", label: "HLE 1837", active: true },
        ],
      },
      {
        series: "eupen-photo-0",
        isMain: false,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Eupen/imggzef.jpeg",
        alt: "Eupen HLE 1828 + I10 + 7x M7 + HLE 1837",
        label: "Eupen",
        numbers:
          "1837, 72144, 73032, 79010, 73006, 73010, 72010, 72054, 12773, 1828",
        date: "8 March 2026",
        consist: [
          { kind: "traction", label: "HLE 1828", active: true },
          { kind: "carriage", label: "I10" },
          { kind: "carriage", label: "7x M7" },
          { kind: "traction", label: "HLE 1837", active: true },
        ],
      },
      {
        series: "eupen-photo-0",
        isMain: false,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Eupen/qsfqsfqs.jpeg",
        alt: "Eupen HLE 1828 + I10 + 7x M7 + HLE 1837",
        label: "Eupen",
        numbers:
          "1837, 72144, 73032, 79010, 73006, 73010, 72010, 72054, 12773, 1828",
        date: "8 March 2026",
        consist: [
          { kind: "traction", label: "HLE 1828", active: true },
          { kind: "carriage", label: "I10" },
          { kind: "carriage", label: "7x M7" },
          { kind: "traction", label: "HLE 1837", active: true },
        ],
      },
    ],
  },
  hasselt: {
    name: "Hasselt",
    country: "Belgium",
    description: "Rail photography in Hasselt.",
    photos: [
      {
        series: "hasselt-photo-0",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Hasselt/IMG_4814.webp",
        alt: "Hasselt HLE 1914 HLE 1853 + I10 + 8x M7 + HLE 1814",
        label: "Hasselt",
        numbers: "1914, 1853, 12759, 72149, 72049, 73011, 79020, 1814",
        date: "8 March 2026",
        consist: [
          { kind: "traction", label: "HLE 1914", active: true },
          { kind: "traction", label: "HLE 1853", active: false },
          { kind: "carriage", label: "I10" },
          { kind: "carriage", label: "8x M7" },
          { kind: "traction", label: "HLE 1814", active: true },
        ],
      },
      {
        series: "hasselt-photo-0",
        isMain: false,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Hasselt/IMG_4796.webp",
        alt: "Hasselt HLE 1914 HLE 1853 + I10 + 8x M7 + HLE 1814",
        label: "Hasselt",
        numbers: "1914, 1853, 12759, 72149, 72049, 73011, 79020, 1814",
        date: "8 March 2026",
        consist: [
          { kind: "traction", label: "HLE 1914", active: true },
          { kind: "traction", label: "HLE 1853", active: false },
          { kind: "carriage", label: "I10" },
          { kind: "carriage", label: "8x M7" },
          { kind: "traction", label: "HLE 1814", active: true },
        ],
      },
    ],
  },
  leuven: {
    name: "Leuven",
    country: "Belgium",
    description: "Rail photography in Leuven.",
    photos: [
      {
        series: "leuven-photo-0",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Leuven/Leuven_HLE1913M7.webp",
        alt: "Leuven HLE 1913 + 6x M7 ",
        label: "Leuven",
        numbers: "1913",
        date: "",
        consist: [
          { kind: "traction", label: "HLE 1913", active: true },
          { kind: "traction", label: "6x M7", active: false },
        ],
      },
    ],
  },
  liege: {
    name: "Liege",
    country: "Belgium",
    description: "Rail photography in Liege.",
    photos: [
      {
        series: "liege-photo-0",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Liege/Luik_AM08543.webp",
        alt: "Liege AM08543",
        label: "Liege",
        numbers: "08543, 8543",
        date: "20 July 2024",
        consist: [{ kind: "traction", label: "AM08 543", active: true }],
      },
      {
        series: "liege-photo-1",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Liege/IMG_4723.webp",
        alt: "Liege 6x m7",
        label: "Liege",
        numbers: "75199, 73174, 73208, 73209, 79041, 76044",
        date: "8 March 2026",
        consist: [{ kind: "traction", label: "6x M7", active: true }],
      },
      {
        series: "liege-photo-2",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Liege/IMG_4734.webp",
        alt: "Liege HLE 1873",
        label: "Liege",
        numbers: "1873, 11819, 11814, 12906, 19820",
        date: "8 March 2026",
        consist: [
          { kind: "traction", label: "HLE 1873", active: true },
          { kind: "carriage", label: "4x I11", active: true },
        ],
      },
      {
        series: "liege-photo-3",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Liege/IMG_4742 2.webp",
        alt: "Liege MR08 504",
        label: "Liege",
        numbers: "8504, 08504, 12906, 19820",
        date: "8 March 2026",
        consist: [{ kind: "traction", label: "AM08 504", active: true }],
      },
      {
        series: "liege-photo-4",
        isMain: true,
        operator: "Arriva",
        src: "../images/Belgium/Liege/IMG_4749.webp",
        alt: "Liege Stadler FLIRT 3",
        label: "Liege",
        numbers: "554",
        date: "8 March 2026",
        consist: [{ kind: "traction", label: "Stadler FLIRT 3", active: true }],
      },
    ],
  },
  lier: {
    name: "Lier",
    country: "Belgium",
    description: "Rail photography in Lier.",
    photos: [
      {
        series: "lier-photo-0",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Lier/Lier_M6HLE1819.webp",
        alt: "Lier 8x M6 + HLE 18/19",
        label: "Lier",
        numbers: "",
        date: "",
        consist: [
          { kind: "carriage", label: "8x M6", active: true },
          { kind: "traction", label: "HLE 18/19", active: true },
        ],
      },
      {
        series: "lier-photo-1",
        isMain: true,
        operator: "NMBS/SNCB",
        src: "../images/Belgium/Lier/Lier_MW4124MW41MW41MW41.webp",
        alt: "Lier MW4124 + MW41 + MW41 + MW41",
        label: "Lier",
        numbers: "4124",
        date: "27 May 2024",
        consist: [
          { kind: "traction", label: "MW41 24", active: true },
          { kind: "traction", label: "MW41", active: true },
          { kind: "traction", label: "MW41", active: true },
          { kind: "traction", label: "MW41", active: true },
        ],
      },
    ],
  },
  luchtbal: {
    name: "Luchtbal",
    country: "Belgium",
    description: "Rail photography in Luchtbal.",
    photos: [
      {
        series: "luchtbal-photo-0",
        isMain: true,
        operator: "Eurostar",
        src: "../images/Belgium/Luchtbal/Luchtbal_E320.webp",
        alt: "Luchtbal E320 4029",
        label: "Luchtbal",
        numbers: "4029",
        date: "",
        consist: [{ kind: "traction", label: "E320 4029", active: true }],
      },
    ],
  },
  mechelen: {
    name: "Mechelen",
    country: "Belgium",
    description: "Rail photography in Mechelen.",
    photos: [
      {
        series: "mechelen-photo-0",
        isMain: true,
        operator: "NMBS/SNCB, NS",
        src: "../images/Belgium/Mechelen/Mechelen_TRAXXICRTRAXX.webp",
        alt: "Mechelen TRAXX 186 205 + 7x ICR + TRAXX",
        label: "Mechelen",
        numbers: "186 205, 2813",
        date: "24 October 2024",
        consist: [
          { kind: "traction", label: "TRAXX 186 205", active: true },
          { kind: "carriage", label: "7x ICR" },
          { kind: "traction", label: "TRAXX", active: true },
        ],
      },
    ],
  },
  schaerbeek: {
    name: "Schaerbeek",
    country: "Belgium",
    description: "Rail photography in Schaerbeek.",
    photos: [
      {
        series: "schaerbeek-photo-0",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Belgium/Schaerbeek/Schaerbeek_Vectron1293181.webp",
        alt: "Schaerbeek Vectron 1293 181",
        label: "Schaerbeek",
        numbers: "1293 181",
        date: "7 January 2026",
        consist: [
          { kind: "traction", label: "Vectron 1293 181", active: true },
        ],
      },
    ],
  },
  paris: {
    name: "Paris",
    country: "France",
    description: "Rail photography in Paris.",
    photos: [
      {
        series: "paris-photo-0",
        isMain: true,
        operator: "SNCF",
        src: "../images/France/Paris/Paris_TGVDuplex245.jpeg",
        alt: "Paris TGV Duplex 245",
        label: "Paris",
        numbers: "245",
        date: "23 April 2025",
        consist: [{ kind: "traction", label: "TGV Duplex 245", active: true }],
      },
    ],
  },
  aachen: {
    name: "Aachen",
    country: "Germany",
    description: "Rail photography in Aachen.",
    photos: [
      {
        series: "aachen-photo-0",
        isMain: true,
        operator: "DB",
        src: "../images/Germany/Aachen/Aachen_DoStoBR146005.webp",
        alt: "Aachen 5x DoSto + BR146 005",
        label: "Aachen",
        numbers: "146 005",
        date: "16 February 2024",
        consist: [
          { kind: "carriage", label: "5x DoSto", active: true },
          { kind: "traction", label: "BR146 005", active: true },
        ],
      },
    ],
  },
  dusseldorf: {
    name: "Dusseldorf",
    country: "Germany",
    description: "Rail photography in Dusseldorf.",
    photos: [
      {
        series: "dusseldorf-photo-0",
        isMain: true,
        operator: "DB",
        src: "../images/Germany/Dusseldorf/Dusseldorf_BR14657235xStadlerKISS.webp",
        alt: "Dusseldorf BR146 572-3 + 5x Stadler KISS",
        label: "Dusseldorf",
        numbers: "146 572-3, 146 572 3, 146 572",
        date: "10 December 2025",
        consist: [
          { kind: "traction", label: "BR146 572-3", active: true },
          { kind: "carriage", label: "5x Stadler KISS", active: true },
        ],
      },
    ],
  },
  luxembourg: {
    name: "Luxembourg",
    country: "Luxembourg",
    description: "Rail photography in Luxembourg.",
    photos: [
      {
        series: "luxembourg-photo-0",
        isMain: true,
        operator: "CFL",
        src: "../images/Luxembourg/Luxembourg/Luxembourg_TRAXX40185xTwindexxVario.webp",
        alt: "Luxembourg TRAXX 4018 + 5x Twindexx Vario",
        label: "Luxembourg",
        numbers: "4018",
        date: "4 July 2025",
        consist: [
          { kind: "traction", label: "TRAXX 4018", active: true },
          { kind: "carriage", label: "5x Twindexx Vario" },
        ],
      },
    ],
  },
  roosendaal: {
    name: "Roosendaal",
    country: "Netherlands",
    description: "Rail photography in Roosendaal.",
    photos: [
      {
        series: "roosendaal-photo-0",
        isMain: true,
        operator: "NMBS/SNCB, NS",
        src: "../images/Netherlands/Roosendaal/Roosendaal_TRAXX1861217xI11TRAXX.webp",
        alt: "Roosendaal TRAXX 186 121 + 7x I11 + TRAXX",
        label: "Roosendaal",
        numbers: "186 121",
        date: "1 June 2025",
        consist: [
          { kind: "traction", label: "TRAXX 186 121", active: true },
          { kind: "carriage", label: "7x I11" },
          { kind: "traction", label: "TRAXX", active: true },
        ],
      },
    ],
  },
  amsterdam: {
    name: "Amsterdam",
    country: "Netherlands",
    description: "Rail photography in Amsterdam.",
    photos: [
      {
        series: "amsterdam-photo-0",
        isMain: true,
        operator: "NS",
        src: "../images/Netherlands/Amsterdam/Amsterdam_NS_VIRM_8631.jpeg",
        alt: "Amsterdam NS VIRM",
        label: "Amsterdam",
        numbers: "8636",
        date: "",
        consist: [{ kind: "traction", label: "VIRM 8636", active: true }],
      },
      {
        series: "amsterdam-photo-0",
        isMain: false,
        operator: "NS",
        src: "../images/Netherlands/Amsterdam/Amsterdam_NS_VIRM_9525.jpeg",
        alt: "Amsterdam NS VIRM 8636",
        label: "Amsterdam",
        numbers: "8636",
        date: "",
        consist: [{ kind: "traction", label: "VIRM 8636", active: true }],
      },
      {
        series: "amsterdam-photo-2",
        isMain: true,
        operator: "DB",
        src: "../images/Netherlands/Amsterdam/Amsterdam_ICE3neo_Eurostar.jpeg",
        alt: "Amsterdam ICE 3 neo with Eurostar",
        label: "Amsterdam",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "E320 ", active: true },
          {
            kind: "traction",
            label: "Eurostar PBA",
            active: false,
            showOnCard: false,
            filterKey: "pba",
            filterLabel: "PBA",
          },
        ],
      },
      {
        series: "amsterdam-photo-3",
        isMain: true,
        operator: "NS, ÖBB",
        src: "../images/Netherlands/Amsterdam/Amsterdam_NS_Vectron_193733.jpeg",
        alt: "Amsterdam NS Vectron 193 733 + NightJet",
        label: "Amsterdam",
        numbers: "193 733",
        date: "",
        consist: [
          { kind: "traction", label: "Vectron 193 733", active: true },
          { kind: "carriage", label: "NightJet", active: false },
        ],
      },
      {
        series: "amsterdam-photo-3",
        isMain: false,
        operator: "NS, ÖBB",
        src: "../images/Netherlands/Amsterdam/Amsterdam_Nightjet.jpeg",
        alt: "Amsterdam NS Vectron 193 733 + NightJet",
        label: "Amsterdam",
        numbers: "193 733",
        date: "",
        consist: [
          { kind: "traction", label: "Vectron 193 733", active: true },
          { kind: "carriage", label: "NightJet", active: false },
        ],
      },
      {
        series: "amsterdam-photo-5",
        isMain: true,
        operator: "Eurostar",
        src: "../images/Netherlands/Amsterdam/Amsterdam_Eurostar_4003.jpeg",
        alt: "Amsterdam Eurostar 4002",
        label: "Amsterdam",
        numbers: "4002",
        date: "",
        consist: [{ kind: "traction", label: "E320 4003", active: true }],
      },
      {
        series: "amsterdam-photo-5",
        isMain: false,
        operator: "Eurostar",
        src: "../images/Netherlands/Amsterdam/Amsterdam_Eurostar_4003_Rear.jpeg",
        alt: "Amsterdam Eurostar 4003 rear view",
        label: "Amsterdam",
        numbers: "4003",
        date: "",
        consist: [{ kind: "traction", label: "Eurostar 4003", active: true }],
      },
      {
        series: "amsterdam-photo-6",
        isMain: true,
        operator: "Rail Force One",
        src: "../images/Netherlands/Amsterdam/Amsterdam_RailForceOne_193946.jpeg",
        alt: "Amsterdam Rail Force One 193 946",
        label: "Amsterdam",
        numbers: "193 946",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Vectron 193 946",
            active: true,
            filterKey: "vectron",
            filterLabel: "Vectron",
          },
        ],
      },
      {
        series: "amsterdam-photo-7",
        isMain: true,
        operator: "NS",
        src: "../images/Netherlands/Amsterdam/Amsterdam_NS_VIRM_8631_Rear.jpeg",
        alt: "Amsterdam NS VIRM rear view",
        label: "Amsterdam",
        numbers: "8655",
        date: "",
        consist: [{ kind: "traction", label: "VIRM 8655", active: true }],
      },
    ],
  },
  vienna: {
    name: "Vienna",
    country: "Austria",
    description: "Rail photography in Vienna.",
    photos: [
      {
        series: "vienna-photo-1",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_5047011.jpeg",
        alt: "Vienna ÖBB 5047 011-1",
        label: "Vienna",
        numbers: "5047 011-1",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Class 5047 011-1",
            active: true,
            filterKey: "class-5047",
            filterLabel: "Class 5047",
          },
        ],
      },
      {
        series: "vienna-photo-2",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_1116167.jpeg",
        alt: "Vienna ÖBB 1116 167",
        label: "Vienna",
        numbers: "1116 167",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus 1116 167",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-3",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_1116193.jpeg",
        alt: "Vienna ÖBB 1116 193",
        label: "Vienna",
        numbers: "1116 193",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus 1116 193",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-4",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_4020302.jpeg",
        alt: "Vienna ÖBB 4020 302-8",
        label: "Vienna",
        numbers: "4020 302-8",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Class 4020 302-8",
            active: true,
            filterKey: "class-4020",
            filterLabel: "Class 4020",
          },
        ],
      },
      {
        series: "vienna-photo-4",
        isMain: false,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_4020305.jpeg",
        alt: "Vienna ÖBB 4020 305-1",
        label: "Vienna",
        numbers: "4020 305-1",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Class 4020 302-8",
            active: true,
            filterKey: "class-4020",
            filterLabel: "Class 4020",
          },
        ],
      },
      {
        series: "vienna-photo-5",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_Cityjet_Doubledecker.jpeg",
        alt: "Vienna ÖBB Cityjet doubledecker",
        label: "Vienna",
        numbers: "",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "KISS",
            active: true,
            filterKey: "kiss",
            filterLabel: "KISS",
          },
        ],
      },
      {
        series: "vienna-photo-6",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_1116199.jpeg",
        alt: "Vienna ÖBB 1116 199",
        label: "Vienna",
        numbers: "1116 199",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus 1116 199",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-7",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_Railjet_8090729.jpeg",
        alt: "Vienna ÖBB Railjet 80-90.729",
        label: "Vienna",
        numbers: "80-90 729",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Steuerwagen 80-90.729",
            active: true,
            filterKey: "steuerwagen",
            filterLabel: "Steuerwagen",
          },
        ],
      },
      {
        series: "vienna-photo-8",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_1116182_Army.jpeg",
        alt: "Vienna ÖBB 1116 182 Army Vectron",
        label: "Vienna",
        numbers: "1116 182",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus 1116 182",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-9",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_4024017.jpeg",
        alt: "Vienna ÖBB 4024 017-7",
        label: "Vienna",
        numbers: "4024 017-7",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Class 4024 017-7",
            active: true,
            filterKey: "class-4024",
            filterLabel: "Class 4024",
          },
        ],
      },
      {
        series: "vienna-photo-10",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_1116111.jpeg",
        alt: "Vienna ÖBB 1116 111",
        label: "Vienna",
        numbers: "1116 111",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus 1116 111",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-11",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_2070041.jpeg",
        alt: "Vienna ÖBB 2070 041",
        label: "Vienna",
        numbers: "2070 041",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Class 2070 041",
            active: true,
            filterKey: "class-2070",
            filterLabel: "Class 2070",
          },
        ],
      },
      {
        series: "vienna-photo-12",
        isMain: false,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_Cityjet_Marchegg_Wide.jpeg",
        alt: "Vienna ÖBB Cityjet Marchegg wide view",
        label: "Vienna",
        numbers: "",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Class 4024 054-0",
            active: true,
            filterKey: "class-4024",
            filterLabel: "Class 4024",
          },
        ],
      },
      {
        series: "vienna-photo-12",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_Cityjet_Marchegg.jpeg",
        alt: "Vienna ÖBB Cityjet Marchegg",
        label: "Vienna",
        numbers: "",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Class 4024 054-0",
            active: true,
            filterKey: "class-4024",
            filterLabel: "Class 4024",
          },
        ],
      },
      {
        series: "vienna-photo-13",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_Cityjet_Crossing.jpeg",
        alt: "Vienna ÖBB Cityjet crossing",
        label: "Vienna",
        numbers: "",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Desiro ML 4746 113",
            active: true,
            filterKey: "desiro-ml",
            filterLabel: "Desiro ML",
          },
        ],
      },
      {
        series: "vienna-photo-14",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_Cityjet_Glueck.jpeg",
        alt: "Vienna ÖBB Cityjet Glueck",
        label: "Vienna",
        numbers: "",
        date: "",
        consist: [
          {
            kind: "carriage",
            label: "4x CityShuttle",
            active: true,
            filterKey: "CityShuttle",
            filterLabel: "CityShuttle",
          },
          {
            kind: "traction",
            label: "Tarus 1116",
            active: true,
            filterKey: "tarus",
            filterLabel: "Tarus",
          },

          {
            kind: "traction",
            label: "Desiro ML",
            active: false,
            showOnCard: false,
            filterKey: "desiro-ml",
            filterLabel: "Desiro ML",
          },
        ],
      },
      {
        series: "vienna-photo-15",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_Cityjet_Stockerau.jpeg",
        alt: "Vienna ÖBB Cityjet Stockerau",
        label: "Vienna",
        numbers: "",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Desiro ML 4746 117",
            active: true,
            filterKey: "desiro-ml",
            filterLabel: "Desiro ML",
          },
        ],
      },
      {
        series: "vienna-photo-16",
        operator: "ZSSK",
        src: "../images/Austria/Vienna/Vienna_ZSSK_263003_Angle.jpeg",
        alt: "Vienna ZSSK 263 003-6 angle view",
        label: "Vienna",
        numbers: "263 003-6",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus 1116 193",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-16",
        isMain: false,
        operator: "ZSSK",
        src: "../images/Austria/Vienna/Vienna_ZSSK_263003_Side.jpeg",
        alt: "Vienna ZSSK 263 003-6 side view",
        label: "Vienna",
        numbers: "263 003-6",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-16",
        isMain: false,
        operator: "ZSSK",
        src: "../images/Austria/Vienna/Vienna_ZSSK_263003_Wide.jpeg",
        alt: "Vienna ZSSK 263 003-6 wide view",
        label: "Vienna",
        numbers: "263 003-6",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-17",
        isMain: true,
        operator: "MÁV-START",
        src: "../images/Austria/Vienna/Vienna_HSTART_470005.jpeg",
        alt: "Vienna H-START 470 005",
        label: "Vienna",
        numbers: "470 005",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus 470 005",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-17",
        isMain: false,
        operator: "H-START",
        src: "../images/Austria/Vienna/Vienna_HSTART_470005_Front.jpeg",
        alt: "Vienna H-START 470 005 front view",
        label: "Vienna",
        numbers: "470 005",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Taurus 470 005",
            active: true,
            filterKey: "taurus",
            filterLabel: "Taurus",
          },
        ],
      },
      {
        series: "vienna-photo-18",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_1293134.jpeg",
        alt: "Vienna ÖBB 1293 134",
        label: "Vienna",
        numbers: "1293 124",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Vectron 1293 124",
            active: true,
            filterKey: "vectron",
            filterLabel: "Vectron",
          },
        ],
      },
      {
        series: "vienna-photo-19",
        isMain: true,
        operator: "CD",
        src: "../images/Austria/Vienna/Vienna_CD_193576.jpeg",
        alt: "Vienna CD 193 576-6 Bobo",
        label: "Vienna",
        numbers: "193 576-6",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Vectron 193 576-6",
            active: true,
            filterKey: "vectron",
            filterLabel: "Vectron",
          },
        ],
      },
      {
        series: "vienna-photo-20",
        isMain: true,
        operator: "ÖBB",
        src: "../images/Austria/Vienna/Vienna_OEBB_Doubledecker_8633210.jpeg",
        alt: "Vienna ÖBB 86-33 210-4",
        label: "Vienna",
        numbers: "86-33 210-4",
        date: "",
        consist: [
          {
            kind: "traction",
            label: "Tarus 1116",
            active: true,
            filterKey: "tarus",
            filterLabel: "Tarus",
          },
          {
            kind: "carriage",
            label: "4x CityShuttle",
            active: false,
            filterKey: "CityShuttle",
            filterLabel: "CityShuttle",
          },
        ],
      },
    ],
  },
  bratislava: {
    name: "Bratislava",
    country: "Slovakia",
    description: "Rail photography in Bratislava.",
    photos: [
      {
        series: "bratislava-photo-0",
        isMain: true,
        operator: "ZSSK",
        src: "../images/Slovakia/Bratislava/Bratislava_ZSSK_263003.jpeg",
        alt: "Bratislava ZSSK 263 003-6",
        label: "Bratislava",
        numbers: "263 003-6",
        date: "",
        consist: [{ kind: "traction", label: "Škoda 263 003-6", active: true }],
      },
      {
        series: "bratislava-photo-0",
        isMain: false,
        operator: "ZSSK",
        src: "../images/Slovakia/Bratislava/Bratislava_ZSSK_263003_Side.jpeg",
        alt: "Bratislava ZSSK 263 003-6 side view",
        label: "Bratislava",
        numbers: "263 003-6",
        date: "",
        consist: [{ kind: "traction", label: "Škoda 263 003-6", active: true }],
      },
      {
        series: "bratislava-photo-0",
        isMain: false,
        operator: "ZSSK",
        src: "../images/Slovakia/Bratislava/Bratislava_ZSSK_263003_Wide.jpeg",
        alt: "Bratislava ZSSK 263 003-6 wide view",
        label: "Bratislava",
        numbers: "263 003-6",
        date: "",
        consist: [{ kind: "traction", label: "Škoda 263 003-6", active: true }],
      },
    ],
  },
  london: {
    name: "London",
    country: "United Kingdom",
    description: "Rail photography in London.",
    photos: [
      {
        series: "london-photo-0",
        isMain: true,
        operator: "Eurostar",
        src: "../images/United Kingdom/London/London_Class3733206.webp",
        alt: "London Class 373 3206",
        label: "London",
        numbers: "373 3206, 3206",
        date: "7 February 2026",
        consist: [{ kind: "traction", label: "Class 373 3206", active: true }],
      },
      {
        series: "london-photo-1",
        isMain: true,
        operator: "Great Western Railway",
        src: "../images/United Kingdom/London/qscqcc.jpeg",
        alt: "London Class 802 104",
        label: "London",
        numbers: "802 104, 104",
        date: "7 February 2026",
        consist: [{ kind: "traction", label: "Class 802 104", active: true }],
      },
      {
        series: "london-photo-2",
        isMain: true,
        operator: "Heatrow Express",
        src: "../images/United Kingdom/London/qscqsc.jpeg",
        alt: "London Class 387 140",
        label: "London",
        numbers: "387 140, 140",
        date: "7 February 2026",
        consist: [{ kind: "traction", label: "Class 387 140", active: true }],
      },
      {
        series: "london-photo-3",
        isMain: true,
        operator: "Great Western Railway",
        src: "../images/United Kingdom/London/qscqscc.jpeg",
        alt: "London Class 387 156",
        label: "London",
        numbers: "387 156, 156",
        date: "7 February 2026",
        consist: [{ kind: "traction", label: "Class 387 156", active: true }],
      },
    ],
  },
};
