window.STATIONS_DATA = {
  antwerp: {
    name: "Antwerp",
    country: "Belgium",
    description: "Rail photography in Antwerp.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Antwerp/Antwerp_HLE1804M6.webp",
        alt: "Antwerp HLE 1804 + 8x M6",
        label: "Antwerp",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "HLE 1804", active: true },
          { kind: "carriage", label: "8x M6", active: true },
        ],
      },
    ],
  },
  "brussels-midi": {
    name: "Brussels-Midi",
    country: "Belgium",
    description: "Rail photography in Brussels-Midi.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Brussels-Midi/Brussels_HLE1834NightJet.webp",
        alt: "Brussels-Midi HLE 1834 + NightJet",
        label: "Brussels-Midi",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "HLE 1834", active: true },
          { kind: "carriage", label: "NightJet" },
        ],
      },
    ],
  },
  duffel: {
    name: "Duffel",
    country: "Belgium",
    description: "Rail photography in Duffel.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Duffel/Duffel_M4HLE27.webp",
        alt: "Duffel 7x M4 + HLE 27",
        label: "Duffel",
        numbers: "",
        date: "",
        consist: [
          { kind: "carriage", label: "7x M4", active: true },
          { kind: "traction", label: "HLE 27", active: true },
        ],
      },
    ],
  },
  eupen: {
    name: "Eupen",
    country: "Belgium",
    description: "Rail photography in Eupen.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Eupen/IMG_4764.webp",
        alt: "Eupen HLE 1828 + 7x M7 + 1x I10 + HLE 1837",
        label: "Eupen",
        numbers: "1837, 72144, 73032, 79010, 73006, 73010, 72010, 72054, 12773, 1828",
        date: "8 March 2026",
        consist: [
          { kind: "traction", label: "HLE 1828", active: true },
          { kind: "carriage", label: "7x M7" },
          { kind: "carriage", label: "I10" },
          { kind: "traction", label: "HLE 1837", active: true },
        ],
      },
    ],
  },
  hasselt: {
    name: "Hasselt",
    country: "Belgium",
    description: "Rail photography in Hasselt.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Hasselt/IMG_4814.webp",
        alt: "Hasselt HLE 1914",
        label: "Hasselt",
        numbers: "",
        date: "",
        consist: [{ kind: "traction", label: "HLE 1914", active: true }],
      },
      {
        isMain: false,
        src: "../images/Belgium/Hasselt/IMG_4796.webp",
        alt: "Hasselt HLE 1814",
        label: "Hasselt",
        numbers: "",
        date: "",
        consist: [{ kind: "traction", label: "HLE 1814", active: true }],
      },
    ],
  },
  leuven: {
    name: "Leuven",
    country: "Belgium",
    description: "Rail photography in Leuven.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Leuven/Leuven_HLE1913M7.webp",
        alt: "Leuven HLE 1913 + 6x M7 ",
        label: "Leuven",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "HLE 1913", active: true },
          { kind: "traction", label: "6x M7", active: false },
        ],
      },
    ],
  },
  liege: {
    name: "Liege",
    country: "Belgium",
    description: "Rail photography in Liege.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Liege/Luik_AM08543.webp",
        alt: "Liege AM08543",
        label: "Liege",
        numbers: "",
        date: "",
        consist: [{ kind: "traction", label: "AM08 543", active: true }],
      },
            {
              isMain: false,
        src: "../images/Belgium/Liege/IMG_4723.webp",
        alt: "Liege 6x m7",
        label: "Liege",
        numbers: "75199, 73174, 73208, 73209, 79041, 76044",
        date: "8 March 2026",
        consist: [{ kind: "traction", label: "6x M7", active: true }],
      },
         {
           isMain: false,
        src: "../images/Belgium/Liege/IMG_4734.webp",
        alt: "Liege HLE 1873",
        label: "Liege",
        numbers: "1873, 11819, 11814, 12906, 19820",
        date: "8 March 2026",
        consist: [{ kind: "traction", label: "HLE 1873", active: true },
              { kind: "carriage", label: "4x I11", active: true },
        ],
      },
      {
        isMain: false,
        src: "../images/Belgium/Liege/IMG_4742 2.webp",
        alt: "Liege MR08 504",
        label: "Liege",
        numbers: "8504, 08504, 12906, 19820",
        date: "8 March 2026",
        consist: [{ kind: "traction", label: "AM08 504", active: true },
        ],
      },
          {
            isMain: false,
        src: "../images/Belgium/Liege/IMG_4749.webp",
        alt: "Liege Stadler FLIRT 3",
        label: "Liege",
        numbers: "554",
        date: "8 March 2026",
        consist: [{ kind: "traction", label: "Stadler FLIRT 3", active: true },
        ],
      },
    ],
  },
  lier: {
    name: "Lier",
    country: "Belgium",
    description: "Rail photography in Lier.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Lier/Lier_M6HLE1819.webp",
        alt: "Lier 8x M6 + HLE 18/19",
        label: "Lier",
        numbers: "",
        date: "",
        consist: [
          { kind: "carriage", label: "8x M6", active: true },
          { kind: "traction", label: "HLE 18/19", active: true },
        ],
      },
      {
        isMain: false,
        src: "../images/Belgium/Lier/Lier_MW4124MW41MW41MW41.webp",
        alt: "Lier MW4124 + MW41 + MW41 + MW41",
        label: "Lier",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "MW41 24", active: true },
          { kind: "traction", label: "MW41", active: true },
          { kind: "traction", label: "MW41", active: true },
          { kind: "traction", label: "MW41", active: true },
        ],
      },
    ],
  },
  luchtbal: {
    name: "Luchtbal",
    country: "Belgium",
    description: "Rail photography in Luchtbal.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Luchtbal/Luchtbal_E320.webp",
        alt: "Luchtbal E320",
        label: "Luchtbal",
        numbers: "",
        date: "",
        consist: [{ kind: "traction", label: "E320", active: true }],
      },
    ],
  },
  mechelen: {
    name: "Mechelen",
    country: "Belgium",
    description: "Rail photography in Mechelen.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Mechelen/Mechelen_TRAXXICRTRAXX.webp",
        alt: "Mechelen TRAXX 186 205 + 7x ICR + TRAXX",
        label: "Mechelen",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "TRAXX 186 205", active: true },
          { kind: "carriage", label: "7x ICR" },
          { kind: "traction", label: "TRAXX", active: true },
        ],
      },
    ],
  },
  schaerbeek: {
    name: "Schaerbeek",
    country: "Belgium",
    description: "Rail photography in Schaerbeek.",
    photos: [
      {
        isMain: true,
        src: "../images/Belgium/Schaerbeek/Schaerbeek_Vectron1293181.webp",
        alt: "Schaerbeek Vectron 1293 181",
        label: "Schaerbeek",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "Vectron 1293 181", active: true },
        ],
      },
    ],
  },
  paris: {
    name: "Paris",
    country: "France",
    description: "Rail photography in Paris.",
    photos: [
      {
        isMain: true,
        src: "../images/France/Paris/Paris_TGVDuplex245.jpeg",
        alt: "Paris TGV Duplex 245",
        label: "Paris",
        numbers: "",
        date: "",
        consist: [{ kind: "traction", label: "TGV Duplex 245", active: true }],
      },
    ],
  },
  aachen: {
    name: "Aachen",
    country: "Germany",
    description: "Rail photography in Aachen.",
    photos: [
      {
        isMain: true,
        src: "../images/Germany/Aachen/Aachen_DoStoBR146005.webp",
        alt: "Aachen 5x DoSto + BR146 005",
        label: "Aachen",
        numbers: "",
        date: "",
        consist: [
          { kind: "carriage", label: "5x DoSto", active: true },
          { kind: "traction", label: "BR146 005", active: true },
        ],
      },
    ],
  },
  dusseldorf: {
    name: "Dusseldorf",
    country: "Germany",
    description: "Rail photography in Dusseldorf.",
    photos: [
      {
        isMain: true,
        src: "../images/Germany/Dusseldorf/Dusseldorf_BR14657235xStadlerKISS.webp",
        alt: "Dusseldorf BR146 572-3 + 5x Stadler KISS",
        label: "Dusseldorf",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "BR146 572-3", active: true },
          { kind: "carriage", label: "5x Stadler KISS", active: true },
        ],
      },
    ],
  },
  luxembourg: {
    name: "Luxembourg",
    country: "Luxembourg",
    description: "Rail photography in Luxembourg.",
    photos: [
      {
        isMain: true,
        src: "../images/Luxembourg/Luxembourg/Luxembourg_TRAXX40185xTwindexxVario.webp",
        alt: "Luxembourg TRAXX 4018 + 5x Twindexx Vario",
        label: "Luxembourg",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "TRAXX 4018", active: true },
          { kind: "carriage", label: "5x Twindexx Vario" },
        ],
      },
    ],
  },
  roosendaal: {
    name: "Roosendaal",
    country: "Netherlands",
    description: "Rail photography in Roosendaal.",
    photos: [
      {
        isMain: true,
        src: "../images/Netherlands/Roosendaal/Roosendaal_TRAXX1861217xI11TRAXX.webp",
        alt: "Roosendaal TRAXX 186 121 + 7x I11 + TRAXX",
        label: "Roosendaal",
        numbers: "",
        date: "",
        consist: [
          { kind: "traction", label: "TRAXX 186 121", active: true },
          { kind: "carriage", label: "7x I11" },
          { kind: "traction", label: "TRAXX", active: true },
        ],
      },
    ],
  },
  london: {
    name: "London",
    country: "United Kingdom",
    description: "Rail photography in London.",
    photos: [
      {
        isMain: true,
        src: "../images/United Kingdom/London/London_Class3733206.webp",
        alt: "London Class 373 3206",
        label: "London",
        numbers: "",
        date: "",
        consist: [{ kind: "traction", label: "Class 373 3206", active: true }],
      },
    ],
  },
};
